server:
  port: 8088

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: demo-app
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8088/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/demo
            authorization-uri: http://keycloak:8080/realms/demo/protocol/openid-connect/auth
            token-uri: http://keycloak:8080/realms/demo/protocol/openid-connect/token
            user-info-uri: http://keycloak:8080/realms/demo/protocol/openid-connect/userinfo
            jwk-set-uri: http://keycloak:8080/realms/demo/protocol/openid-connect/certs
            user-name-attribute: preferred_username
